// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9UCoKyw3vkcCWpN6yX0IKxHtUrurjxj4',
    appId: '1:254938635207:web:21189eb77ebcb4a93f57e2',
    messagingSenderId: '254938635207',
    projectId: 'smartpool-57e1d',
    authDomain: 'smartpool-57e1d.firebaseapp.com',
    databaseURL: 'https://smartpool-57e1d-default-rtdb.firebaseio.com',
    storageBucket: 'smartpool-57e1d.appspot.com',
    measurementId: 'G-LXGXJ7P0D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsXnbBTRsgFMNdJJQZtzVrmDMinbJuUaw',
    appId: '1:254938635207:android:ec925516f5b1fd383f57e2',
    messagingSenderId: '254938635207',
    projectId: 'smartpool-57e1d',
    databaseURL: 'https://smartpool-57e1d-default-rtdb.firebaseio.com',
    storageBucket: 'smartpool-57e1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrubFOyuoeLDZn49ys1TH6OpCxTLVtS7g',
    appId: '1:254938635207:ios:ec21e92f81b8be523f57e2',
    messagingSenderId: '254938635207',
    projectId: 'smartpool-57e1d',
    databaseURL: 'https://smartpool-57e1d-default-rtdb.firebaseio.com',
    storageBucket: 'smartpool-57e1d.appspot.com',
    iosClientId: '254938635207-nkkhmvu7m2eddfeg5h7mgbvl2si3c5dd.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloWorld',
  );
}
