pipeline {
   agent any
   stages {
            stage('git checkout') {
                echo 'test_pipeline'
            }
                 steps{
 sh "mvn package -Dmaven.test.skip=true"
            }

        }

    }

}