stage 'Checkout'
 node('slave') {
  deleteDir()
  checkout scm
}

stage 'Build & Archive Apk'
 node('slave') {
  sh 'export ANDROID_SERIAL=192.168.56.101:5555 ; ./build.sh'
  step([$class: 'ArtifactArchiver', artifacts: 'smart-pool/build/app/outputs/flutter-apk/app.apk'])
 }

stage 'Run Tests'
 node('slave') {
  sh 'export ANDROID_SERIAL=192.168.56.101:5555 ; ./runtests.sh'
  publishHTML(target: [reportDir: 'smart-pool/lib/main', reportFiles: 'main.dart', reportName: 'Testes Instrumentados'])
  step([$class: 'JUnitResultArchiver', testResults: 'smart-pool/build/app/outputs/flutter-apk/'])
}